os: linux
dist: bionic

language: node_js
node_js:
  - lts/*

cache:
  - npm

before_install:
  - cd website
  - node -v
  - npm -v
  - npm -g install now
  - npm -g install yarn
  - now -v
  - yarn -v

install:
  - yarn

scripts:
  - yarn build

deploy:
  provider: script
  script:
    - mkdir -p .vercel
    - echo $VERCEL_CONFIG > .vercel/project.json
    - now --prod -t $VERCEL_TOKEN
    - rm -rf .vercel
  skip_cleanup: true
  on:
    branch: develop
